[toolchain]
package_manager = "yarn"
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cryptolift = "HHBLrTyLRaSLhVUhJw75MMi1d4heggk6SWB77fJdouKT"

[programs.devnet]
cryptolift = "HHBLrTyLRaSLhVUhJw75MMi1d4heggk6SWB77fJdouKT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
